Controllers/ForgotIdController.cs
using ShoppingProjectA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoppingProjectA.Controllers
{
    public class ForgotIdController : Controller
    {
        private ShoppingContext sc;
        public ForgotIdController()
        {
            sc = new ShoppingContext();
        }
        // GET: ForgotId
        public ActionResult ForgotIdIndex()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ForgotIdIndex(ForgotId forgotId)
        {
            var reg = sc.Registrations.Where(m => m.ContactNumber == forgotId.ContactNumber && m.Email == forgotId.Email).FirstOrDefault();
            if (reg != null)
            {
                if (reg.BirthCity == forgotId.BirthCity && reg.Strength == forgotId.Strength && reg.BestFriendName == forgotId.BestFriend)
                {
                    forgotId.Message = reg.UserId + "is your userid";
                }
                else
                {
                    forgotId.Message = "You entered wrong details!";
                }
            }
            else
            {
                forgotId.Message = "You entered wrong details!";
            }
            return View(forgotId);
        }
        public ActionResult ForgotPwIndex()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ForgotPwIndex(ForgotPw forgotPw)
        {
            var reg = sc.Registrations.Where(m => m.UserId == forgotPw.UserId).FirstOrDefault();
            if (reg != null)
            {
                if (reg.BirthCity == forgotPw.BirthCity && reg.Strength == forgotPw.Strength && reg.BestFriendName == forgotPw.BestFriend)
                {
                    return RedirectToAction("PwReset",new { userid = forgotPw.UserId });
                }
                else
                {
                    forgotPw.Message = "You entered wrong details!";
                }
                
            }
            else
            {
                forgotPw.Message = "You entered wrong details!";
            }
            return View(forgotPw);


        }
        public ActionResult PwReset(string userid)
        {
            Session["userid"] = userid;
            return View();
        }
        [HttpPost]
        public ActionResult PwReset(PwReset pw)
        {
            string user = (string)Session["userid"];

            var reg = sc.Registrations.SingleOrDefault(m => m.UserId == user);
            if(reg != null)
            {
                reg.Password = pw.Password;
                reg.RePassword = pw.RePassword;
                sc.SaveChanges();
                pw.Message = "Password changed successfully, please login again!";

            }

            return View(pw);
        }
    }
}

Controllers/LoginController.cs
using ShoppingProjectA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CaptchaMvc.HtmlHelpers;
using System.Web.Security;

namespace ShoppingProjectA.Controllers
{
    
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult LoginIndex()
        {
            return View();
        }
        [HttpPost]
        public ActionResult LoginIndex(Registration reg)
        {
            using (ShoppingContext sc = new ShoppingContext())
            {
                var logus = sc.Registrations.Where(m => m.UserId == reg.UserId).FirstOrDefault();
                var logpw = sc.Registrations.Where(m => m.Password == reg.Password).FirstOrDefault();
                    if (logus == null )
                    {
                        reg.ErrorMesssage = reg.UserId + " user id is not registered! please register.";
                        return View("LoginIndex", reg);
                    }
                    else if (logpw == null)
                    {
                        reg.ErrorMesssage = "Wrong password!";
                        return View("LoginIndex", reg);
                    }
                    else if (!(this.IsCaptchaValid("Captcha is not valid")))
                    {
                        reg.ErrorMesssage = "Invalid captcha";
                        return View("LoginIndex", reg);
                    }
                
                    else
                    {
                        if (logus.Category == "Admin")
                        {
                        Session["userid"] = logus.UserId;
                            string Name = logus.FirstName;
                            return RedirectToAction("AdminIndex", "Admin", new { name = Name });
                        }
                        else
                        {
                        Session["userid"] = logus.UserId;
                        var shop = (from s in sc.shops where s.UserId == logus.UserId select s).FirstOrDefault();
                            if (shop == null)
                            {
                                Session["userid"] = logus.UserId;
                                return RedirectToAction("CreateProfile", "ShopOwner");
                            }
                            else
                            {
                                Session["Sid"] = shop.Id;
                                Session["Sownername"] = shop.ShopOwnerName;
                                Session["Suserid"] = shop.UserId;
                                string Name = logus.FirstName;
                                string Userid = logus.UserId;
                                return RedirectToAction("ShopOwnerIndex", "ShopOwner", new { Id = (int)Session["Sid"] });
                            }
                        }
                    }
            }
        }
         public ActionResult Logout()
         {
            

            Session.Clear();
            return RedirectToAction("LoginIndex","Login");
         }

    }
}

Controllers/RegistrationController.cs
using ShoppingProjectA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoppingProjectA.Controllers
{
    public class RegistrationController : Controller
    {
        private ShoppingContext sc;
        public RegistrationController()
        {
            sc = new ShoppingContext();
        }
        // GET: Registration
        public ActionResult Index()
        {
            var getCategories = sc.Categories.ToList();
            SelectList list = new SelectList(getCategories, "Name", "Name");
            ViewBag.listOfCategories = list;
            List<SelectListItem> gender = new List<SelectListItem>();

            gender.Add(new SelectListItem { Text = "Male", Value = "Male" });

            gender.Add(new SelectListItem { Text = "Female", Value = "Female" });

            gender.Add(new SelectListItem { Text = "Others", Value = "Others" });

            ViewData["GenderType"] = gender;
            return View();
        }

        [HttpPost]
        public ActionResult Index(Registration regis)
        {
            var getCategories = sc.Categories.ToList();
            SelectList list = new SelectList(getCategories, "Name", "Name");
            ViewBag.listOfCategories = list;
            List<SelectListItem> gender = new List<SelectListItem>();

            gender.Add(new SelectListItem { Text = "Male", Value = "Male" });

            gender.Add(new SelectListItem { Text = "Female", Value = "Female" });

            gender.Add(new SelectListItem { Text = "Others", Value = "Others" });

            ViewData["GenderType"] = gender;
            bool mem = IsMember(regis.UserId);
            if (!mem)
            {
                sc.Registrations.Add(regis);
                sc.SaveChanges();
                ViewBag.Name = regis.FirstName;
                return RedirectToAction("LoginIndex", "Login");
            }
            else
            {
                regis.ErrorMesssage = "UserId already exists, Please select other";
                return View(regis);
            }
                
        }
        public ActionResult termsAndConditions()
        {
            return View();
        }

        public bool IsMember(string UserID)
        {
            // This will return if a given user exists
            return sc.Registrations.Any(u => u.UserId == UserID);
        }
    }
}

Views/Login/LoginIndex.cshtml
@using CaptchaMvc.HtmlHelpers;

@model ShoppingProjectA.Models.Registration
@{
    ViewBag.Title = "LoginIndex";
}

<h2 style="color: navy; text-align:center">Login Now!</h2>


<style>
    #lbl {
        padding-right: 10px;
    }

    .blank_row {
        height: 30px;
    }

    #formBody {
        padding-left: 80px;
    }

    #logform {
        margin-top: 10px;
        padding-top: 30px;
        margin-left: 400px;
        height: 550px;
        width: 550px;
        border: double;
        border-color: navy;
    }

    .log {
        margin-right: 30px;
    }
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>



    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div id="logform">
            <div class="form-horizontal" id="formBody">
                <br />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="log">

                    <div class="form-group">
                        @Html.LabelFor(model => model.UserId, htmlAttributes: new { @id = "lbl", @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @id = "us", @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="blank_row">

                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Password, htmlAttributes: new { @id = "lbl", @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @id = "pw", @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div>
                    <div style="margin-left: 100px;">
                        @* @Html.MathCaptcha()  *@
                        @Html.Captcha(4)
                    </div>
                    <br />
                    <p style="color: red">  @Html.DisplayFor(m => m.ErrorMesssage) </p>

                    <p> If not registered, please @Html.ActionLink("Register Here", "Index", "Registration")</p>
                    <p>Forgot Userid? please @Html.ActionLink("Click here","ForgotIdIndex","ForgotId")</p>
                    <p>Forgot Password? reset @Html.ActionLink("Here", "ForgotPwIndex", "ForgotId")</p>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input id="reg" style="color:white; background-color:green; margin-right: 30px; margin-left: 10px;" type="submit" value="Login" class="btn btn-default" />

                        <input style="color:black; background-color:white" type="reset" value="Reset" class="btn btn-default" />
                    </div>
                </div>

            </div>
        </div>
    }
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    